### ISSUE TITLE
Incidencia - Flujos de Trabajo - Error al crear una Llamada indicando duración minutos sin duración horas

### ISSUE THREAD

**Issue by jordiSTIC** [SinergiaTIC/SinergiaCRM#474]
## Descripción del problema
Si un Flujo de Trabajo que al activarse cree un registro de Llamada, y en la definición de la llamada a crear se informa la "Duración (minutos)" pero no la "Duración (horas)", el Flujo de Trabajo falla.

Por ejemplo, si el FdT se activa al modificar una Persona, al guardar la Persona, se produce un error "500" y no se crea la Llamada correspondiente.
El error que se produce es:
```
Uncaught Error: Call to a member function asDb() on bool in /application/sinergiacrm/modules/Calls/Call.php:187
Stack trace:
#0 /application/sinergiacrm/modules/AOW_Actions/actions/actionCreateRecord.php(428): Call->save()
#1 /application/sinergiacrm/modules/AOW_Actions/actions/actionCreateRecord.php(169): actionCreateRecord->set_record()
#2 /application/sinergiacrm/modules/AOW_WorkFlow/AOW_WorkFlow.php(1078): actionCreateRecord->run_action()
#3 /application/sinergiacrm/modules/AOW_WorkFlow/AOW_WorkFlow.php(229): AOW_WorkFlow->run_actions()
#4 /application/sinergiacrm/include/utils/LogicHook.php(260): AOW_WorkFlow->run_bean_flows()
#5 /application/sinergiacrm/include/utils/LogicHook.php(201): LogicHook->process_hooks()
#6 /application/sinergiacrm/data/SugarBean.php(3207): LogicHook->call_custom_logic()
#7 /application/sinergiacrm/data/SugarBean.php(2431): SugarBean->call_custom_logic()
#8 /application/sinergiacrm/include/SugarObjects/templates/person/Person.php(210): SugarBean->save()
#9 /application/sinergia in /application/sinergiacrm/modules/Calls/Call.php on line 187
```

Analizando el problema, se observa que únicamente se produce si se indica la duración minutos sin la duración horas. En los casos en que se indique la duración horas sin la duración minutos, o no se indique ninguna de las dos, funciona correctamente.

Para evitar el problema hasta su resolución, indicando la duración horas = 0 no se produce el error

## Cómo reproducir el problema
1. Crear un Flujo de Trabajo sobre un módulo, que se ejecute al guardar, en los registros modificados y con ejecuciones repetitivas
2. El Flujo de Trabajo creará un registro del módulo Llamadas con:
    1. Asunto: "Prueba"
    2. Estado: "Planificada"
    3. Dirección: "Salida"
    4. Fecha inicio: "Ahora + 2 horas"
    5. Duración (minutos): 15
3. Guardar el Flujo de Trabajo
4. Modificar un registro para que se ejecute el Flujo de Trabajo
5. Verificar que se produce un error al guardar el registro y no se ha creado la Llamada

## Comportamiento esperado
No debería haberse producido error al intentar crear la Llamada.

## Solución propuesta
Si debe calcular la duración y no está informado el campo Duración (horas) se debería entender que es 0

**Comment by jordiSTIC** [comment]
Posiblemente relacionado con https://github.com/SinergiaTIC/SinergiaCRM/pull/445
